spring:
  profiles:
    active:
      - deploy
      - mysqlDB
  http:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
image:
  receiptPath: 'receipt/'
paypal:
  mode: sandbox
  client:
    app: AWI3P3RoATfuQ0urPRAFpWvjkh4L63I8-GrBRhJR6-v7dtwUB7YTEpufHjNvxgjUOtHutM1QH9RVSRjS
    secret: EKqmg_QXsJZOfTDo8EO5P2d6x6F_QUyZ1GT94nfM9IlOW13VDFJXaDNFzaEli2miIVyUOdMpdI634_zG
---
spring:
  profiles: zenon
image:
  urlPath: 'http://localhost:8080/'
  dirPath: '/Users/zenon/Desktop/woostore/images/'
---
spring:
  profiles: zenonnb
image:
  urlPath: 'http://localhost:8080/'
  dirPath: 'C:\Users\sizen\Desktop\Projects\woostore\images\'
---
spring:
  profiles: iammiind
image:
  urlPath: 'http://localhost:8080/'
  dirPath: '/Users/iammiind/Desktop/woostore/images/'
---
spring:
  profiles: deploy
image:
  urlPath: 'http://54.245.150.45:8080/woostore/'
  dirPath: '/home/ubuntu/images/'
---
spring:
  profiles: inMemoryDB
  datasource:
    url: jdbc:h2:mem:woostore;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
---
spring:
  profiles: mysqlDB
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  datasource:
      url: jdbc:mysql://localhost/wooStore?useSSL=false
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: woowoo